### ISSUE TITLE
Add clippy check to github actions CI

### ISSUE THREAD

**Issue by garlic-hub** [sharkdp/fd#1511]
Hello. I recently submitted a PR to fix all active clippy warnings (which was merged, thank you). With that done, I'm wondering if there's interest to automatically flag a warning on any PR that introduces a clippy warning?

**Comment by garlic-hub** [comment]
I'm thinking something like this. Not too familiar with github actions
```yml
  check_cargo_clippy:
    name: Ensure 'cargo clippy' warnings have been addressed
    runs-on: ubuntu-20.04
    steps:
    - uses: dtolnay/rust-toolchain@stable
    - uses: actions/checkout@v4
    - run: cargo clippy --all-targets --all-features
```
